// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqzLYHFOX5OENSjvh2k_9vBO2rsozLi4',
    appId: '1:640405228305:web:66d621d010a04e4e1f5ab0',
    messagingSenderId: '640405228305',
    projectId: 'imagelab-db7d4',
    authDomain: 'imagelab-db7d4.firebaseapp.com',
    storageBucket: 'imagelab-db7d4.firebasestorage.app',
    measurementId: 'G-E7GLQTSH3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGu_S9TpHSt7FwNSctfxkcUPZkxWEvc6E',
    appId: '1:640405228305:android:51cb85242bdc1dd31f5ab0',
    messagingSenderId: '640405228305',
    projectId: 'imagelab-db7d4',
    storageBucket: 'imagelab-db7d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5LEiTZ1sVtT1Wct-by8gP-yfcL9MSZg',
    appId: '1:640405228305:ios:40478ae4aab6541c1f5ab0',
    messagingSenderId: '640405228305',
    projectId: 'imagelab-db7d4',
    storageBucket: 'imagelab-db7d4.firebasestorage.app',
    iosBundleId: 'com.example.cw08image',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5LEiTZ1sVtT1Wct-by8gP-yfcL9MSZg',
    appId: '1:640405228305:ios:40478ae4aab6541c1f5ab0',
    messagingSenderId: '640405228305',
    projectId: 'imagelab-db7d4',
    storageBucket: 'imagelab-db7d4.firebasestorage.app',
    iosBundleId: 'com.example.cw08image',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfqzLYHFOX5OENSjvh2k_9vBO2rsozLi4',
    appId: '1:640405228305:web:fe638199bd87e0e11f5ab0',
    messagingSenderId: '640405228305',
    projectId: 'imagelab-db7d4',
    authDomain: 'imagelab-db7d4.firebaseapp.com',
    storageBucket: 'imagelab-db7d4.firebasestorage.app',
    measurementId: 'G-S2HLDY3WY7',
  );
}
